<?xml version="1.0"?>
<!-- Copyright (c) 2020 The Plankton Authors.
     All rights reserved.

     This source code is derived from UUV Simulator
     (https://github.com/uuvsimulator/uuv_simulator)
     Copyright (c) 2016-2019 The UUV Simulator Authors
     licensed under the Apache license, Version 2.0
     cf. 3rd-party-licenses.txt file in the root directory of this source tree.

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="prop_mesh_file" value="file://$(find minerva_description)/meshes/prop.dae"/>

  <!-- Thruster joint and link snippet -->
  <xacro:macro name="thruster_macro"
    params="namespace parent_link thruster_id *origin">
    <xacro:thruster_module_first_order_basic_fcn_macro
      namespace="${namespace}"
      parent_link="${parent_link}"
      thruster_id="${thruster_id}"
      mesh_filename="${prop_mesh_file}"
      dyn_time_constant="0.05"
      rotor_constant="0.00031">

      <xacro:insert_block name="origin"/>
    </xacro:thruster_module_first_order_basic_fcn_macro>
  </xacro:macro>
 
<!-- Torpedo-Shape 

  <xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="0">
    <origin xyz="${length_1 + length_joint + 0.470} 0 ${2*radius}" rpy="${0*d2r} ${0*d2r} ${-90*d2r}"/>
  </xacro:thruster_macro>
  <xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="1">
    <origin xyz="${length_1 + length_joint + 0.470} 0 0" rpy="${0*d2r} ${0*d2r} ${90*d2r}"/>
  </xacro:thruster_macro>
  <xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="2">
    <origin xyz="${length_1 + length_joint + 0.370} ${radius+0.08} ${radius}" rpy="${0*d2r} ${45*d2r} ${0*d2r}"/>
  </xacro:thruster_macro>
  <xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="3">
    <origin xyz="${length_1 + length_joint + 0.370} ${-radius-0.08} ${radius}" rpy="${0*d2r} ${-45*d2r} ${0*d2r}"/>
  </xacro:thruster_macro>

  <xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="4">
    <origin xyz="${length_1 + length_2 + 2*length_joint + 0.670} 0 ${2*radius}" rpy="${0*d2r} ${0*d2r} ${-90*d2r}"/>
  </xacro:thruster_macro>
  <xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="5">
    <origin xyz="${length_1 + length_2 + 2*length_joint + 0.670} 0 0" rpy="${0*d2r} ${0*d2r} ${90*d2r}"/>
  </xacro:thruster_macro>
  <xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="6">
    <origin xyz="${length_1 + length_2 + 2*length_joint + 0.770} ${radius+0.08} ${radius}" rpy="${0*d2r} ${45*d2r} ${0*d2r}"/>
  </xacro:thruster_macro>
  <xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="7">
    <origin xyz="${length_1 + length_2 + 2*length_joint + 0.770} ${-radius-0.08} ${radius}" rpy="${0*d2r} ${-45*d2r} ${0*d2r}"/>
  </xacro:thruster_macro>


  <xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="8">
    <origin xyz="${length_1 + length_2 + length_3 + 3*length_joint + 0.715} 0 ${2*radius}" rpy="${0*d2r} ${0*d2r} ${-90*d2r}"/>
  </xacro:thruster_macro>
  <xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="9">
    <origin xyz="${length_1 + length_2 + length_3 + 3*length_joint + 0.715} 0 0" rpy="${0*d2r} ${0*d2r} ${90*d2r}"/>
  </xacro:thruster_macro>
  <xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="10">
    <origin xyz="${length_1 + length_2 + length_3 + 3*length_joint + 0.815} ${radius+0.08} ${radius}" rpy="${0*d2r} ${45*d2r} ${0*d2r}"/>
  </xacro:thruster_macro>
  <xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="11">
    <origin xyz="${length_1 + length_2 + length_3 + 3*length_joint + 0.815} ${-radius-0.08} ${radius}" rpy="${0*d2r} ${-45*d2r} ${0*d2r}"/>
  </xacro:thruster_macro>
-->




<!-- U-Shape horizontal-->
<!-- 
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="0">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707/2*(length_2+length_joint-2*0.12)} ${0.707/2*(length_2+length_joint-2*0.12)} ${radius}" rpy="${0*d2r} ${0*d2r} ${(-45)*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="1">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707/2*(length_2+length_joint-2*0.12)} ${0.707/2*(length_2+length_joint-2*0.12)} ${-radius}" rpy="${0*d2r} ${0*d2r} ${(135)*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="2">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707/2*(length_2+length_joint-2*(0.22+radius+0.08))} ${0.707/2*(length_2+length_joint-2*(0.22-radius-0.08))} 0" rpy="${0*d2r} ${45*d2r} ${45*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="3">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707/2*(length_2+length_joint-2*(0.22-radius-0.08))} ${0.707/2*(length_2+length_joint-2*(0.22+radius+0.08))} 0" rpy="${0*d2r} ${-45*d2r} ${45*d2r}"/>
</xacro:thruster_macro>


<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="4">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707*(length_2+length_joint)} ${0.707*(length_2+length_joint) + (length_3+length_joint)/2-0.042} ${radius}" rpy="${0*d2r} ${0*d2r} ${0*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="5">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707*(length_2+length_joint)} ${0.707*(length_2+length_joint) + (length_3+length_joint)/2-0.042} ${-radius}" rpy="${0*d2r} ${0*d2r} ${180*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="6">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707*(length_2+length_joint) +radius+0.08} ${(0.707*(length_2+length_joint) + (length_3+length_joint)/2)+0.058} 0" rpy="${0*d2r} ${-45*d2r} ${90*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="7">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707*(length_2+length_joint) -radius-0.08} ${(0.707*(length_2+length_joint) + (length_3+length_joint)/2)+0.058} 0" rpy="${0*d2r} ${45*d2r} ${90*d2r}"/>
</xacro:thruster_macro>


<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="8">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707/2*(length_4+length_joint) -0.707*0.12} ${0.707*(length_2+length_joint + 0.12)+(length_3+length_joint)+0.707/2*(length_4+length_joint)} ${radius}" rpy="${0*d2r} ${0*d2r} ${45*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="9">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707/2*(length_4+length_joint) -0.707*0.12} ${0.707*(length_2+length_joint + 0.12)+(length_3+length_joint)+0.707/2*(length_4+length_joint)} ${-radius}" rpy="${0*d2r} ${0*d2r} ${225*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="10">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707/2*(length_4+length_joint) +0.707*(-0.22+radius+0.08)} ${0.707*(length_2+length_joint+0.22+radius+0.08)+(length_3+length_joint)+0.707/2*(length_4+length_joint)} 0" rpy="${0*d2r} ${-45*d2r} ${135*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="11">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707/2*(length_4+length_joint) +0.707*(-0.22-radius-0.08)} ${0.707*(length_2+length_joint+0.22-radius-0.08)+(length_3+length_joint)+0.707/2*(length_4+length_joint)} 0" rpy="${0*d2r} ${45*d2r} ${135*d2r}"/>
</xacro:thruster_macro>
-->






<!-- U-Shape vertical-->
<!-- -->
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="0">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707/2*(length_2+length_joint-2*0.12+2*radius)} 0 ${-0.707/2*(length_2+length_joint-2*(0.12))+0.707*radius}" rpy="${0*d2r} ${0*d2r} ${-90*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="1">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707/2*(length_2+length_joint-2*0.12-2*radius)} 0 ${-0.707/2*(length_2+length_joint-2*(0.12))-0.707*radius}" rpy="${0*d2r} ${0*d2r} ${90*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="2">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707/2*(length_2+length_joint-2*(0.22))} ${radius+0.08} ${-0.707/2*(length_2+length_joint-2*(0.22))}" rpy="${0*d2r} ${90*d2r} ${0*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="3">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707/2*(length_2+length_joint-2*(0.22))} ${-radius-0.08} ${-0.707/2*(length_2+length_joint-2*(0.22))}" rpy="${0*d2r} ${0*d2r} ${0*d2r}"/>
</xacro:thruster_macro>


<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="4">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707*(length_2+length_joint) +radius} 0 ${-0.707*(length_2+length_joint) - (length_3+length_joint)/2+0.042}" rpy="${0*d2r} ${0*d2r} ${-90*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="5">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707*(length_2+length_joint) -radius} 0 ${-0.707*(length_2+length_joint) - (length_3+length_joint)/2+0.042}" rpy="${0*d2r} ${0*d2r} ${90*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="6">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707*(length_2+length_joint)} ${radius+0.08} ${-(0.707*(length_2+length_joint) + (length_3+length_joint)/2)-0.058}" rpy="${0*d2r} ${135*d2r} ${0*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="7">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707*(length_2+length_joint)} ${-radius-0.08} ${-(0.707*(length_2+length_joint) + (length_3+length_joint)/2)-0.058}" rpy="${0*d2r} ${45*d2r} ${0*d2r}"/>
</xacro:thruster_macro>


<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="8">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707/2*(length_4+length_joint) -0.707*(0.12-radius)} 0 ${-0.707*(length_2+length_joint + 0.12+radius)-(length_3+length_joint)-0.707/2*(length_4+length_joint)}" rpy="${0*d2r} ${0*d2r} ${-90*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="9">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707/2*(length_4+length_joint) -0.707*(0.12+radius)} 0 ${-0.707*(length_2+length_joint + 0.12-radius)-(length_3+length_joint)-0.707/2*(length_4+length_joint)}" rpy="${0*d2r} ${0*d2r} ${90*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="10">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707/2*(length_4+length_joint) +0.707*(-0.22)} ${radius+0.08} ${-0.707*(length_2+length_joint+0.22)-(length_3+length_joint)-0.707/2*(length_4+length_joint)}" rpy="${0*d2r} ${180*d2r} ${0*d2r}"/>
</xacro:thruster_macro>
<xacro:thruster_macro namespace="${namespace}" parent_link="base_link" thruster_id="11">
  <origin xyz="${length_1/2 + length_joint/2 + 0.707/2*(length_4+length_joint) +0.707*(-0.22)} ${-radius-0.08} ${-0.707*(length_2+length_joint+0.22)-(length_3+length_joint)-0.707/2*(length_4+length_joint)}" rpy="${0*d2r} ${90*d2r} ${0*d2r}"/>
</xacro:thruster_macro>
  
</robot>
