<?xml version="1.0"?>
<!-- Copyright (c) 2020 The Plankton Authors.
     All rights reserved.

     This source code is derived from UUV Simulator
     (https://github.com/uuvsimulator/uuv_simulator)
     Copyright (c) 2016-2019 The UUV Simulator Authors
     licensed under the Apache license, Version 2.0
     cf. 3rd-party-licenses.txt file in the root directory of this source tree.

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <!-- includes -->
  <xacro:include filename="$(find uuv_descriptions)/urdf/common.urdf.xacro"/>
  <xacro:include filename="$(find uuv_sensor_ros_plugins)/urdf/sensor_snippets.xacro"/>
  <xacro:include filename="$(find uuv_gazebo_ros_plugins)/urdf/snippets.xacro"/>  

  <!-- Parameters -->
  <xacro:property name="namespace" value="minerva"/>
  <xacro:property name="visual_mesh_file" value="file://$(find minerva_description)/meshes/minerva_v2.dae"/>
  <xacro:property name="prop_mesh_file" value="file://$(find minerva_description)/meshes/prop.dae"/>
  <xacro:property name="base_link_mesh_file" value="file://$(find minerva_description)/meshes/base_link_color.dae"/>
  <xacro:property name="link_2_mesh_file" value="file://$(find minerva_description)/meshes/link_2_color.dae"/>
  <xacro:property name="link_3_mesh_file" value="file://$(find minerva_description)/meshes/link_3_color.dae"/>
  <xacro:property name="link_5_mesh_file" value="file://$(find minerva_description)/meshes/link_5_color.dae"/>
  <xacro:property name="eelume_mesh_file" value="file://$(find minerva_description)/meshes/snake_full.dae"/>

  <!-- Mass, see p.28 in Berg2012 -->
  <xacro:property name="mass" value="199"/>
  <xacro:property name="length_1" value="0.494"/>
  <xacro:property name="length_2" value="1.185"/>
  <xacro:property name="length_3" value="1.435"/>
  <xacro:property name="length_4" value="1.185"/>
  <xacro:property name="length_5" value="0.740"/>
  <xacro:property name="length_joint" value="0.28575"/>
  <xacro:property name="radius" value="0.1" />
  <xacro:property name="length" value="6.181"/>
  <xacro:property name="mass_1" value="${5*mass/(length-length_joint)*length_1}"/>
  <xacro:property name="mass_2" value="${5*mass/(length-length_joint)*length_2}"/>
  <xacro:property name="mass_3" value="${5*mass/(length-length_joint)*length_3}"/>
  <xacro:property name="mass_4" value="${5*mass/(length-length_joint)*length_4}"/>
  <xacro:property name="mass_5" value="${5*mass/(length-length_joint)*length_5}"/>


  <!-- Torpedo-Shape-->
  <!-- 
  <xacro:macro name="minerva_base" params="namespace *gazebo inertial_reference_frame">
    <link name="${namespace}/base_link">
      <visual>
        <origin xyz="${length/2} 0 ${radius}" rpy="0 ${pi/2} 0"/>
        <geometry>                
          <mesh filename="${eelume_mesh_file}" scale="1 1 1"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="${length/2} 0 ${radius}" rpy="0 ${pi/2} 0"/>
        <geometry>
            <cylinder length="${length}" radius="${radius}" />
        </geometry>
      </collision>
      <inertial>
        <mass value="${mass}" />
        <origin xyz="${length/2} 0 ${radius}" rpy="0 ${pi/2} 0"/>
        <inertia ixx="${(1/12) * mass * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
              iyy="${(1/12) * mass * (3*radius*radius + length*length)}" iyz="0.0"
              izz="${(1/2) * mass * (radius*radius)}" />
      </inertial>
    </link>

    <xacro:insert_block name="gazebo"/>

    <xacro:include filename="$(find minerva_description)/urdf/minerva_actuators.xacro"/>
    <xacro:include filename="$(find minerva_description)/urdf/minerva_sensors.xacro"/>

  </xacro:macro>
-->









  <!-- U-Shape -->
  <!-- -->
  <xacro:macro name="minerva_base" params="namespace *gazebo inertial_reference_frame">
    <link name="${namespace}/base_link">
      <visual name="mesh_1">
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>                
          <mesh filename="${base_link_mesh_file}" scale="1 1 1"/>
        </geometry>
      </visual>
      <visual name="joint">
        <origin xyz="${length_1/2+length_joint/4} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${length_joint/2}"/>
        </geometry>
        <material name="black">
          <color rgba="0.0 0.0 0.0 0.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${length_1/2} 0 ${radius}" rpy="0 ${pi/2} 0"/>
        <geometry>
            <cylinder length="${length_1}" radius="${radius}" />
        </geometry>
      </collision>
      <inertial>
        <mass value="${mass_1}" />
        <origin xyz="${length_1/2} 0 ${radius}" rpy="0 ${pi/2} 0"/>
        <inertia ixx="${(1/12) * mass_1 * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
              iyy="${(1/12) * mass_1 * (3*radius*radius + length*length)}" iyz="0.0"
              izz="${(1/2) * mass_1 * (radius*radius)}" />
      </inertial>
    </link>
    


    <joint name="${namespace}/joint_12" type="revolute">
      <origin xyz="${length_1/2 + length_joint/2} 0 0" rpy="0 0 0"/>
      <parent link="${namespace}/base_link"/>
      <child link="${namespace}/link_2"/>
      <axis xyz="0 1 0"/>
      <limit lower="${pi/4-0.001}" upper="${pi/4+0.001}" effort="100" velocity="100"/>
    </joint>


    <link name="${namespace}/link_2">
      <visual>
          <origin xyz="${(length_2+length_joint)/2} 0 0" rpy="0 ${pi/2} 0"/>
          <geometry>                
            <mesh filename="${link_2_mesh_file}" scale="1 1 1"/>
          </geometry>
      </visual>
      <visual name="joint_1">
        <origin xyz="${length_joint/4} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${length_joint/2}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <visual name="joint_2">
        <origin xyz="${length_2+3*length_joint/4} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${length_joint/2}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
          <origin xyz="${(length_2+length_joint)/2} 0 0" rpy="0 ${pi/2} 0"/>
          <geometry>
              <cylinder length="${length_2}" radius="${radius}" />
          </geometry>
      </collision>
      <inertial>
        <mass value="${mass_2}" />
        <origin xyz="${(length_2+length_joint)/2} 0 0" rpy="0 ${pi/2} 0"/>
        <inertia ixx="${(1/12) * mass_2 * (3*radius*radius + length_2*length_2)}" ixy="0.0" ixz="0.0"
              iyy="${(1/12) * mass_2 * (3*radius*radius + length_2*length_2)}" iyz="0.0"
              izz="${(1/2) * mass_2 * (radius*radius)}" />
      </inertial>
    </link>


    <joint name="${namespace}/joint_23" type="revolute">
      <origin xyz="${length_2+length_joint} 0 0" rpy="0 0 0"/>
      <parent link="${namespace}/link_2"/>
      <child link="${namespace}/link_3"/>
      <axis xyz="0 1 0"/>
      <limit lower="${pi/4-0.001}" upper="${pi/4+0.001}" effort="100" velocity="100"/>
    </joint>


    <link name="${namespace}/link_3">
      <visual>
          <origin xyz="${(length_3+length_joint)/2} 0 0" rpy="0 ${pi/2} 0"/> 
          <geometry>                
            <mesh filename="${link_3_mesh_file}" scale="1 1 1"/>
          </geometry>
      </visual>
      <visual name="joint_1">
        <origin xyz="${length_joint/4} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${length_joint/2}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <visual name="joint_2">
        <origin xyz="${length_3+3*length_joint/4} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${length_joint/2}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
          <origin xyz="${(length_3+length_joint)/2} 0 0" rpy="0 ${pi/2} 0"/>
          <geometry>
              <cylinder length="${length_3}" radius="${radius}" />
          </geometry>
      </collision>
      <inertial>
        <mass value="${mass_3}" />
        <origin xyz="${(length_3+length_joint)/2} 0 0" rpy="0 ${pi/2} 0"/>
        <inertia ixx="${(1/12) * mass_3 * (3*radius*radius + length_3*length_3)}" ixy="0.0" ixz="0.0"
              iyy="${(1/12) * mass_3 * (3*radius*radius + length_3*length_3)}" iyz="0.0"
              izz="${(1/2) * mass_3 * (radius*radius)}" />
      </inertial>
    </link>



    <joint name="${namespace}/joint_34" type="revolute">
      <origin xyz="${length_3+length_joint} 0 0" rpy="0 0 0"/>
      <parent link="${namespace}/link_3"/>
      <child link="${namespace}/link_4"/>
      <axis xyz="0 1 0"/>
      <limit lower="${pi/4-0.001}" upper="${pi/4+0.001}" effort="100" velocity="100"/>
    </joint>


    <link name="${namespace}/link_4">
      <visual>
          <origin xyz="${(length_4+length_joint)/2} 0 0" rpy="0 ${pi/2} ${pi}"/>
          <geometry>                
            <mesh filename="${link_2_mesh_file}" scale="1 1 1"/>
          </geometry>
      </visual>
      <visual name="joint_1">
        <origin xyz="${length_joint/4} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${length_joint/2}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <visual name="joint_2">
        <origin xyz="${length_4+3*length_joint/4} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${length_joint/2}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
          <origin xyz="${(length_4+length_joint)/2} 0 0" rpy="0 ${pi/2} 0"/>
          <geometry>
              <cylinder length="${length_4}" radius="${radius}" />
          </geometry>
      </collision>
      <inertial>
        <mass value="${mass_4}" />
        <origin xyz="${(length_4+length_joint)/2} 0 0" rpy="0 ${pi/2} 0"/>
        <inertia ixx="${(1/12) * mass_4 * (3*radius*radius + length_4*length_4)}" ixy="0.0" ixz="0.0"
              iyy="${(1/12) * mass_4 * (3*radius*radius + length_4*length_4)}" iyz="0.0"
              izz="${(1/2) * mass_4 * (radius*radius)}" />
      </inertial>
    </link>




    <joint name="${namespace}/joint_45" type="revolute">
      <origin xyz="${length_4+length_joint} 0 0" rpy="0 0 0"/>
      <parent link="${namespace}/link_4"/>
      <child link="${namespace}/link_5"/>
      <axis xyz="0 1 0"/>
      <limit lower="${pi/4-0.001}" upper="${pi/4+0.001}" effort="100" velocity="100"/>
    </joint>


  
    <link name="${namespace}/link_5">
      <visual>
          <origin xyz="${(length_5+length_joint)/2} 0 0" rpy="0 ${pi/2} 0"/> 
          <geometry>                
            <mesh filename="${link_5_mesh_file}" scale="1 1 1"/>
          </geometry>
      </visual>
      <visual name="joint_test">
        <origin xyz="${length_joint/4} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${length_joint/2}"/>
        </geometry>
      </visual>
      <collision>
          <origin xyz="${(length_5+length_joint)/2} 0 0" rpy="0 ${pi/2} 0"/>
          <geometry>
              <cylinder length="${length_5}" radius="${radius}" />
          </geometry>
      </collision>
      <inertial>
        <mass value="${mass_5}" />
        <origin xyz="${(length_5+length_joint)/2} 0 0" rpy="0 ${pi/2} 0"/>
        <inertia ixx="${(1/12) * mass_5 * (3*radius*radius + length_5*length_5)}" ixy="0.0" ixz="0.0"
              iyy="${(1/12) * mass_5 * (3*radius*radius + length_5*length_5)}" iyz="0.0"
              izz="${(1/2) * mass_5 * (radius*radius)}" />
      </inertial>
    </link>

    
    <xacro:insert_block name="gazebo"/>



    <xacro:include filename="$(find minerva_description)/urdf/minerva_actuators.xacro"/>
    <xacro:include filename="$(find minerva_description)/urdf/minerva_sensors.xacro"/>

  </xacro:macro>





</robot>
